language: ruby
rvm:
  - 2.2
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
branches:
  only:
  - gh-pages
  - /.*/

install: 
  - bundle install

script:
  - bundle exec jekyll build
  # Ignore external certificate errors from https://ci.commonwl.org, ignore '#' and '#top'
  - htmlproofer --allow-hash-href --url-ignore="#top,/https://ci.commonwl.org/" _site/

