notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
    - oicr:S9k4EowgQv9AnbCfEZHSzCsg
sudo: required
services:
- docker

addons:
  postgresql: "9.6"

cache:
  directories:
  - $HOME/.m2
  - /tmp/localstack_install_dir
  - $HOME/.cache/pip

language: java
jdk:
- oraclejdk8

env:
   - EXTRA_MAVEN_VAR="" TESTING_PROFILE="unit-tests"
   - EXTRA_MAVEN_VAR="" TESTING_PROFILE="integration-tests"
   - EXTRA_MAVEN_VAR="cobertura:cobertura coveralls:report" TESTING_PROFILE="unit-tests"
   - EXTRA_MAVEN_VAR="cobertura:cobertura-integration-test coveralls:report" TESTING_PROFILE="integration-tests"
   - EXTRA_MAVEN_VAR="cobertura:cobertura-integration-test coveralls:report" TESTING_PROFILE="toil-integration-tests"
   - EXTRA_MAVEN_VAR="cobertura:cobertura-integration-test coveralls:report" TESTING_PROFILE="regression-integration-tests"

# build lifecycle is before_install, install, before_script, script, after_script

before_install:
- pip install --upgrade pip
# pre-build to check dependencies and look for out-of-sync swagger
- mvn install --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true -V
# start local stack in the background
- pip install --user localstack
- localstack start &
- ./scripts/check-swagger.sh

install:
- docker version
- ./scripts/install-tests.sh

before_script:
- psql -c "create user dockstore with password 'dockstore' createdb;" -U postgres
- psql -c "ALTER USER dockstore WITH superuser;" -U postgres
- psql -c 'create database webservice_test with owner = dockstore;' -U postgres
- export PATH=$PATH:$PWD/dockstore-client/target

script: ./scripts/run-tests.sh

before_cache:
- rm -rf /home/travis/.m2/repository/io/dockstore

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7f1c48703628e3514bb6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
